apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'dcgm-mock'
        scrape_interval: 5s
        static_configs:
          - targets: ['dcgm-mock:9100']
      - job_name: 'kubernetes'
        kubernetes_sd_configs:
          - role: node
