apiVersion: batch/v1
kind: Job
metadata:
  name: rightsizer-smoke-check
spec:
  template:
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: fix-perms
          image: busybox:1.36.1
          command: ["/bin/sh", "-c", "chown -R 1000:1000 /reports || true"]
          volumeMounts:
            - name: reports
              mountPath: /reports
      containers:
        - name: smoke
          image: curlimages/curl:8.2.1
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -euo pipefail
              echo "Checking dcgm-mock /metrics..."
              curl -sfS http://dcgm-mock:9100/metrics | head -n 20 > /tmp/dcgm-metrics.txt
              echo "Querying Prometheus for GPU util sample..."
              # Query Prometheus API for a recent value (write raw JSON)
              curl -sfS 'http://prometheus:9090/api/v1/query?query=DCGM_FI_DEV_GPU_UTIL' -o /tmp/prom-query.json || true
              echo "Writing smoke results to reports PVC..."
              mkdir -p /reports/smoke
              cp /tmp/dcgm-metrics.txt /reports/smoke/dcgm-metrics.txt
              cp /tmp/prom-query.json /reports/smoke/prom-query.json
              echo "SMOKE_OK" > /reports/smoke/status.txt
              # create a tiny single-line index.html so nginx will serve the directory
              echo '<html><body><h1>Smoke outputs</h1><ul><li><a href="./status.txt">status.txt</a></li><li><a href="./dcgm-metrics.txt">dcgm-metrics.txt</a></li><li><a href="./prom-query.json">prom-query.json</a></li></ul></body></html>' > /reports/smoke/index.html
          volumeMounts:
            - name: reports
              mountPath: /reports
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: reports-pvc